### ISSUE TITLE
开启了 git info 但 Travis-CI 自动构建的文章修改日期始终为最新

### ISSUE THREAD

**Issue by he-sb** [reuixiy/hugo-theme-meme#107]
配置文件中修改了：

```toml
enableGitInfo = true
[frontmatter]
    lastmod = ["lastmod", ":git", ":fileModTime", ":default"]
```

博客使用 Travis-CI 自动构建， `.travis.yml` 文件在 [这里](https://github.com/he-sb/tech/blob/master/.travis.yml) 和 [这里](https://github.com/he-sb/Blog/blob/master/.travis.yml) ，这两个博客都是相同的状况；

测试了本地执行 `hugo` 生成的网站中修改日期是正确的 git 时间，但不知为何 Travis-CI 自动构建出来的网站，所有文章的修改日期都变成了触发了自动构建的时间，网上搜了一大圈也没看到有类似的情况……
