### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#150]
最近发现在移动设备的窄视图下顶栏右上角的折叠按钮点击后的展开速度变慢了，与大家的相比能明显看出比较慢，不知道是咋了，目前也就在 config.toml 里面修改了[params]下的 headerBackground.

我也不太懂是哪里出了问题，有朋友知道怎么回事吗？🙉谢谢了🙏

**Comment by dawnow** [comment]
右上角的按钮为三条短横线，它具体展开时的动画可以分解为上下两条横线转动交叉（第一条横线快速转动并下移，第三条横线向右上角倾斜45度），中间的横线随之快速转动并从左侧消失，这个过程在我的博客中像是慢放一样。这玩意是累了吗？🤣

**Comment by reuixiy** [comment]
目前动画的时长直接取决于 [`duration`](https://github.com/dawnow/blog/blob/88d28930533131e80328678960b0ea99c33d030c/config.toml#L726) 参数

**Comment by dawnow** [comment]
> 目前动画的时长直接取决于 [`duration`](https://github.com/dawnow/blog/blob/88d28930533131e80328678960b0ea99c33d030c/config.toml#L726) 参数

哦哦哦我想起来了，前些天好像修改了这个参数，不知道这是干啥的，当时修改完没感觉到啥变化（没意识到），原来这个动画也是由它控制的😮。感谢一休儿指点🎈。其实我是看到了[这位大哥](https://zhix.co/)的博客，我看他文章中的超链接都是暗红色的（这样应该比较好区分），而主题默认的超链接样式都是只有一条灰色的下划线，不知道这个需要怎么设置呀？

**Comment by reuixiy** [comment]
```scss
.post-body {
    p, li, dd, sup, td {
        a {
            color: var(--color-primary);
            text-decoration: none;
        }
    }
}
```
