### ISSUE TITLE
品牌栏SVG颜色填充的亮暗模式切换

### ISSUE THREAD

**Issue by JinhangZhu** [reuixiy/hugo-theme-meme#204]
Hiya！非常感谢你的努力让这个主题这个完善又艺术，我想提一个小feature要求：

在使用SVG作品牌栏时，填充颜色只有一种，亮暗模式下只能保持一种颜色：
```toml
    siteBrandSVG = true
    # 如果是，请将你的 SVG 放到 `SVG.toml` 文
    # 件内，并配置以下项。单位：px。
    siteBrandSVGWidth = 150
    siteBrandSVGHeight = 80
    siteBrandSVGFill = "#fff"
```

请问可不可以设计**light模式下一个颜色，dark模式下一个颜色**呢？如图：

![Ligit-mode-black](https://i.loli.net/2020/06/18/ovegIx8mhQ7NPHO.png)![Dark-mode-white](https://i.loli.net/2020/06/18/RJe7bGtEWnNrDS6.png)
