### ISSUE TITLE
移动端light与dark模式切换时图标转换出现问题

### ISSUE THREAD

**Issue by blleng** [reuixiy/hugo-theme-meme#226]
如图所示：

![bug](https://s1.ax1x.com/2020/07/22/U7APEV.png)

在由light模式切换到dark模式后再切换回light模式时出现此问题，而dark模式无此问题。

meme主题版本：The latest

浏览器环境：
-  Firefox for Android
- Chrome for Android
- Chrome for Linux 模拟移动端

**Comment by reuixiy** [comment]
无法复现，给个链接

**Comment by blleng** [comment]
我的博客BLLENG<https://freezing.cool>

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: reuixiy <notifications@github.com>
发送时间: Saturday, August 8, 2020 1:59:55 PM
收件人: reuixiy/hugo-theme-meme <hugo-theme-meme@noreply.github.com>
抄送: Leng <l0bl@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [reuixiy/hugo-theme-meme] 移动端light与dark模式切换时图标转换出现问题 (#226)


无法复现，给个链接

―

**Comment by reuixiy** [comment]
好像与 https://github.com/reuixiy/hugo-theme-meme/issues/175 有点像，你是参考了我的博客仓库吗？

你可以去 `assets/scss/custom/_custom.scss` 看看，将相关 CSS 代码移除，即可。

**Comment by blleng** [comment]
好的，我去看看

**Comment by blleng** [comment]
```css
@media (max-width: $maxWidth) {
    .nav {
        margin: 2em 0;
    }
    .menu-item .icon {
        display: inline-block;  //应该是这里出问题了吧
    }
    .menu-item-name {
        font-size: 80%;
    }
}
```
