### ISSUE TITLE
尝试添加更多Section

### ISSUE THREAD

**Issue by aozaki-kuro** [reuixiy/hugo-theme-meme#239]
您好，看了您的博客后我也将自己的博客部署为Hugo+MemE，非常棒的主题！这两天也基本完成了调整，但是在新增sections的时候遇到了问题。

我想在原来的life、tech基础上新增一个humanity分类，所以模仿您的config.toml进行了一些微调
```toml
[[menu.main]]
        url = "/humanity/"
        name = "人性"
        weight = 3
        pre = "internal"
        #post = "wpexplorer"
        identifier = "humanity"
```
```toml
mainSections = ["life", "tech", "humanity"]
```
```toml
categoryBy = "sections"
```
主要是这几处

我的content文件夹下是这样的
```sh
.
├── about
│   ├── 0001.jpg      
│   └── _index.md     
├── humanity
│   ├── humanity-00.md
│   └── humanity-01.md
├── life
│   ├── 2020-08-04-ghost-of-tsushima
│   │   ├── 0002.jpg
│   │   └── index.md
│   ├── 2020-08-05-why-blogging
│   │   ├── 0001.jpg
│   │   └── index.md
│   └── 2020-08-07-master-graduation
│       ├── 0001.jpg
│       └── index.md
└── tech
    ├── 2020-08-09-troubled-hugo
    │   ├── 0001.jpg
    │   └── index.md
    └── 2020-08-10-github-action
        ├── 0001.jpg
        └── index.md
```

但是直接部署后跳转“人性”分区报404，查了资料后说需要_index.md？但是我是几乎零基础coding，看了很多资料也完全不知道怎么写的，看了您的博客仓库也没有发现_index.md，所以比较疑惑应该怎么改才能让新的section页面正常生成…希望reuixiy大大不吝赐教🤣
