### ISSUE TITLE
No posts list on homepage when permalink is set

### ISSUE THREAD

**Issue by grizz-pl** [reuixiy/hugo-theme-meme#282]
Hi when I add content to posts/ and set in config:
```toml
[permalinks]
    posts ="/:slug/"
[params]
   homeLayout = "posts"
```
there is no list of post’s summary on homepage but the newest post is shown.
