### ISSUE TITLE
Easy-to-access font variable

### ISSUE THREAD

**Issue by peterkos** [reuixiy/hugo-theme-meme#283]
It'd be nice if fonts were set via a variable, e.g.:
```css
--font-title: "Fira Sans", sans-serif;
--font-body: "Fira Sans", sans-serif;
--font-nav: "Fira Sans", sans-serif;
```
(rough list)

Currently, to change the fonts, it's a bit messy:
```scss
.post-title, .post-subtitle, .post-nav, .related-title, thead, dt,
.post-body h1,
.post-body h2,
.post-body h3,
.post-body h4,
.post-body h5,
.post-body h6, {
    font-family: "Fira Sans", sans-serif;
}
```
(And that's only a subset of the selectors!)
