### ISSUE TITLE
[bug]生成RSS时出错

### ISSUE THREAD

**Issue by Magic-King** [reuixiy/hugo-theme-meme#307]
刚把博客从hexo迁移至hugo，但是发现rss生成错误

> This page contains the following errors:
> error on line 7337 at column 9: PCDATA invalid Char value 19
> Below is a rendering of the page up to the first error.

经过Google之后，发现好像是缺少相关的xml头所导致，想问下这是由于rss模板错误所导致的嘛？还是因为我配置不当。

以下是我hugo配置中rss相关的部分

```toml
# Atom 文件格式的媒体类型
[mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

# MemE 主题自定义的 Atom 模板
[outputFormats.SectionsAtom]
    mediaType = "application/atom+xml"
    baseName = "atom"

# MemE 主题自定义的 RSS 模板
[outputFormats.SectionsRSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

# lunr.js 的搜索索引
[outputFormats.SearchIndex]
     mediaType = "application/json"
     baseName = "search"

# Hugo 的输出控制
[outputs]
    page = ["HTML"]
    home = ["HTML", "SectionsAtom", "SectionsRSS", "SearchIndex"]
    # home = ["HTML", "SectionsAtom", "SectionsRSS"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

# RSS & Atom 文章数限制
[services.rss]
    limit = -1

# 站点的描述
    siteDescription = "Magic's Blog.<br>NowYouSeeMe."
    # 说明：用于 HTML 的头部元数据、JSON-LD、
    #      Open Graph、Atom、RSS
   ######################################
    # Atom & RSS

    # 是否包括全文内容
    includeContent = true
```
