### ISSUE TITLE
It seems that data/Socials.toml url setting does not support tencent protocol 😢

### ISSUE THREAD

**Issue by makisevon** [reuixiy/hugo-theme-meme#353]
I create a new `Socials.toml` file in my site `data` directory

```toml
# ...

[[socials]]
    id = "qq"
    url = "tencent://message/?uin=xxx"
    icon = "qq"
    title = "QQ"
    weight = 4

# ...
```

Then I get

```html
<a href="#ZgotmplZ" target="_blank" rel="external noopener" title="QQ">
<!-- ... -->
</a>
```

Is it a bug of hugo or something?
