### ISSUE TITLE
分享按钮不工作

### ISSUE THREAD

**Issue by javioustlj** [reuixiy/hugo-theme-meme#375]
在about页面里面的分享按钮是正常工作的。
但是在post里面的分享按钮，却无法正常工作。
https://javioustlj.github.io/book/yifanhua/ 这个页面的分享按钮就不工作。
https://javioustlj.github.io/about/ 这个页面的分享按钮正常工作。

**Comment by tianheg** [comment]
可能的原因：你设置的分享按钮，和 footer 贴得太近了

![image](https://user-images.githubusercontent.com/52186032/160311657-2ec5b6e6-addf-4dce-9577-43fd338c9af2.png)

**Comment by javioustlj** [comment]
> 

请问如何修改

> 

请问如何修改footer和分享之间的距离呢？ 我的菜单设置具体问题是什么呢，能详细说一下吗？

非常感谢

**Comment by javioustlj** [comment]
> 可能的原因：你设置的分享按钮，和 footer 贴得太近了
> 
> ![image](https://user-images.githubusercontent.com/52186032/160311657-2ec5b6e6-addf-4dce-9577-43fd338c9af2.png)
> 
> 我进行了缩放，发现可以分享
> 
> ![image](https://user-images.githubusercontent.com/52186032/160311901-bc5f0253-e24a-4574-ac4c-b9032f53e962.png)
> 
> 我还发现你的菜单设置有些问题

请问如何修改footer和分享之间的距离呢？ 我的菜单设置具体问题是什么呢，能详细说一下吗？

非常感谢

**Comment by tianheg** [comment]
关于「分享按钮」：

在 [`themes/meme/layouts/partials/components/post-share.html`](https://github.com/javioustlj/hugo-theme-meme/blob/2a7732ffa5/layouts/partials/components/post-share.html#L117) 这里加了一个 `<br>`。

关于「菜单」：

在 [`config.toml`](https://github.com/javioustlj/javioustlj.github.io/blob/main/config.toml#L246-L266) 进行了修改：

```toml
    [[menu.main]]
        url = "/life/"
        name = "生活"
        weight = 1
        pre = "internal"
        # post = "grav"
        identifier = "life"
    [[menu.main]]
        pageref = "/book/"
        name = "读书"
        weight = 1
        pre = "internal"
        # post = "grav"
        identifier = "book"
    # [[menu.main]]
    #     pageref = "/tech/"
    #     name = "技术"
    #     weight = 3
    #     pre = "internal"
    #     post = "wpexplorer"
    #     identifier = "tech"
```
