### ISSUE TITLE
Sections的问题

### ISSUE THREAD

**Issue by isTrih** [reuixiy/hugo-theme-meme#404]
我在`config.toml`如下设置
```toml
 categoryBy = "sections"
# 删除了categories
[taxonomies]
    category = ""
    tag = "tags"
```

并且按照提示于`content/categories/`新建`_index.md`
```
content
│   
└───about
│   │   _index.md
│
└───categories
│   │   _index.md
│
└───blogroll
│   │   _index.md
│   
└───posts
│    │   _index.md
│    │
│    └───life
│        │   _index.md
│        │   my-from-soil.md
│    └───website
│        │   _index.md
│        │   hellohugo.md
│        │   helloworld.md
```

但是我的分类界面并没有正常工作。[分类界面](https://blog.trih.icu/categories/)
同时posts界面的文字也未正常工作。
使用版本[hugo_extended_0.101.0_macOS-ARM64](https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_macOS-ARM64.tar.gz)
谢谢大佬！
