### ISSUE TITLE
/about/ No Page, don't work

### ISSUE THREAD

**Issue by ISouthRain** [reuixiy/hugo-theme-meme#422]
```toml
# config.toml
    [[menu.main]]
        pageref = "/about/"
        name = "About"
        weight = 5
        pre = "internal"
        post = "user-circle"#user-circle
```
have file:
--- content
----- about.md
content/about.md: 
```markdown
---
title: "About"
comment: false
---
# About, This About page
```

Click home page Menu "About", Not work!! 
Not /about/ Page

**Comment by here-Leslie-Lau** [comment]
How did you solve it, I also encountered

**Comment by ISouthRain** [comment]
config.toml
```toml
        url = "/about/"
        name = "About"
        weight = 5
        pre = "internal"
        post = "user-circle"
```
