### ISSUE TITLE
Baidu tongji support

### ISSUE THREAD

**Issue by Scottdyt** [reuixiy/hugo-theme-meme#45]
Hi @reuixiy , it is me again. I am wondering if you can kindly add [Baidu Tongji ](https://tongji.baidu.com/web/welcome/login) supoort for your theme, this can be auxiliary option for google analytics.

**Comment by he-sb** [comment]
> Hi @reuixiy , it is me again. I am wondering if you can kindly add [Baidu Tongji ](https://tongji.baidu.com/web/welcome/login) supoort for your theme, this can be auxiliary option for google analytics.

Hey buddy, Baidu is a **rogue** company of China, I highly recommend **not** to use any service of its, I mean it.

**Comment by reuixiy** [comment]
Hi @Scottdyt,

I'm afraid I won't add this feature, because you can do it yourself.

1. `~/blog/layouts/partials/custom/script.html`

    ```go
    {{ partial "third-party/baidu-analytics.html" . }}
    ```

2. `~/blog/layouts/partials/third-party/baidu-analytics.html`

    ```go
    {{ if and .Site.Params.enableBaiduAnalytics (eq hugo.Environment "production") }}
        <script>
            var _hmt = _hmt || [];
            (function () {
                var script = document.createElement('script');
                script.src = 'https://hm.baidu.com/hm.js?{{ .Site.Params.baiduAnalyticsID }}';
                document.head.appendChild(script);
            })();
        </script>
    {{ end }}
    ```

3. `~/blog/layouts/partials/custom/instantclick.html`

    ```go
    {{ if and .Site.Params.enableBaiduAnalytics (eq hugo.Environment "production") }}
        <script data-no-instant>
            InstantClick.on('change', function () {
                _hmt.push(['_trackPageview', location.pathname + location.search]);
            });
        </script>
    {{ end }}
    ```

4. `~/blog/config.toml`

    ```toml
    [params]
        ######################################
        # 自行添加的百度统计

        # 说明：仅在生产环境（production）下渲染

        enableBaiduAnalytics = true
        baiduAnalyticsID = ""
    ```
