### ISSUE TITLE
极简页脚在英文的关于页面里不显示

### ISSUE THREAD

**Issue by xeon-chow** [reuixiy/hugo-theme-meme#454]
首先感谢作者提供的主题！

配置关于页面的极简页脚时，在中文关于页里可以显示，但是英语关于页面不能显示。相关配置应该都写在config.toml文件里了，这里给出英语部分的配置段：

``` toml
    [[language.en.menu.socials]]
        url = "mailto:enitxeon@gmail.com"
        weight = 3
        name = ""
        identifier = "mail"
        pre = "external"
        post = "envelope"
    [[language.en.menu.socials]]
        url = "https://instagram.com/xeon_chow/"
        weight = 1
        name = ""
        identifier = "instagram"
        pre = "external"
        post = "instagram"
    [[language.en.menu.socials]]
        url = "https://www.threads.net/@xeon_chow"
        weight = 2
        name = ""
        identifier = "threads"
        pre = "external"
        post = "threads"
    [[language.en.menu.links]]
        pageref = "/"
        name = " "
        identifier = "home"
        weight = 1
        pre = "internal"
        post = "home"
    [[language.en.menu.links]]
        pageref = "/tags/"
        name = " "
        identifier = "tags"
        weight = 2
        pre = "internal"
        post = "tags"
    [[language.en.menu.links]]
        url = "/rss.xml/"
        weight = 3
        name = ""
        identifier = "rss"
        pre = "external"
        post = "rss"
```

请问是我多语言配置漏了什么选项吗？谢谢。
