### ISSUE TITLE
How to make multilingual Websites?

### ISSUE THREAD

**Issue by Syralist** [reuixiy/hugo-theme-meme#89]
How do I need to organize my posts for multilanguage websites?
I dont want to use subdirectories but suffixes on the files. From the Hugo documentation this should be possible.

**Comment by reuixiy** [comment]
Assume `de` is your default content language:

1. change [`defaultContentLanguage`](https://github.com/reuixiy/hugo-theme-meme/blob/0d14242bfe588efe12c0c11d3cb200c9d45e4eda/config-examples/en/config.toml#L18) to `de`

2. add `[languages]` params to the bottom of `config.toml`, e.g.
    ```toml
    ##########################################
    # Configure Multilingual Mode

    # de
    [languages.de]
        languageName = "Deutsch"
        weight = 1
        languageCode = "de-DE"

    # en
    [languages.en]
        languageName = "English"
        weight = 2
        languageCode = "en-US"
    ```

3. add a `de` post, e.g. `hello-world.de.md`

4. set [`enableLangToggle`](https://github.com/reuixiy/hugo-theme-meme/blob/0d14242bfe588efe12c0c11d3cb200c9d45e4eda/config-examples/en/config.toml#L1225) to `true`

5. `hugo server`
